version: "3"

services:
  m01-nodered:
    image: nodered/node-red:2.2.3-16
    container_name: m01-nodered
    ports:
      - 1880:1880
    volumes:
      - ./nodered-data:/data

  m01-influxdb:
    image: influxdb:2.2-alpine
    container_name: m01-influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-data:/var/lib/influxdb2

  m01-grafana:
    image: grafana/grafana:9.3.2-ubuntu
    container_name: m01-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
